- name: Daemon reload
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart prometheus-node-exporter
  ansible.builtin.service:
    name: prometheus-node-exporter
    state: restarted
    enabled: yes
