- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: present


- name: Replace a file
  ansible.builtin.template:
    src: default
    dest: /etc/nginx/sites-enabled/default
  notify: Restart nginx
