- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present


- name: Copy a default configuration file
  ansible.builtin.template:
    src: default
    dest: /etc/nginx/sites-enabled/default
  notify:
     - Restart nginx
     - Restart prometheus-nginx-exporter

- name: Start Nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
