- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: present


- name: Replace a file
  ansible.builtin.copy:
    src: default
    dest: /etc/nginx/sites-enabled/default
  when: "ansible_service_mgr == 'systemd'"
  notify: Restart nginx
