- name: Download InfluxDB exporter package
  ansible.builtin.get_url:
    url: https://github.com/carlpett/influxdb_stats_exporter/releases/download/v0.1.1/influx_stats_exporter_linux_amd64
    dest: /usr/local/bin/
    mode: 0755

#- name: Start InfluxDB exporter
#  ansible.builtin.service:
#    name: influxdb_stats_exporter
#    state: started
#    enabled: yes
