- name: Install rsyslog
  ansible.builtin.apt:
     name: rsyslog
     state: present

- name: Add file with a target address for logs
  ansible.builtin.template:
     src: 50-telegraf.conf
     dest: /etc/rsyslog.d/50-telegraf.conf
  notify: Restart rsyslog

- name: Start rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: started
    enabled: yes
