- name: Install Grafana
  ansible.builtin.get_url:
    url: "https://dl.grafana.com/oss/release/grafana_9.1.7_amd64.deb"
    dest: "/tmp/grafana.deb"
    mode: '0644'

#- name: Install grafana
#  ansible.builtin.apt:
#    name: grafana
#    state: present

#- name: Restart grafana after changes are applied
#  ansible.builtin.copy:
#    src: main.json
#    dest: /etc/grafana/grafana.ini
#  notify: Restart grafana
