- name: Generate repository key
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key

- name: Grafana repository
  ansible.builtin.apt_repository:
    repo: deb https://packages.grafana.com/enterprise/deb stable main

- name: Install grafana
  ansible.builtin.apt:
    name: grafana
    state: present

- name: Restart grafana after changes are applied
  ansible.builtin.template:
    src: grafana.ini
    dest: /etc/grafana/grafana.ini
  notify: Restart grafana

- name: Start grafana
  ansible.builtin.service:
    name: grafana-server
    state: started
    enabled: yes

- name: Add file main.json to the VM
  ansible.builtin.copy:
    src: main.json
    dest: /etc/grafana/provisioning/dashboards
