- name: Install uWSGI
  ansible.builtin.apt:
    update_cache: yes
    name: uwsgi
    state: present

- name: Install uWSGI plugin Python3
  ansible.builtin.apt:
    update_cache: yes
    name: uwsgi-plugin-python3
    state: present

- name: Add the uWSGI configuration for AGAMA application
  ansible.builtin.copy:
    src: agama.ini
    dest: /etc/uwsgi/apps-enabled/agama.ini
    owner: agama
  when: "ansible_service_mgr == 'systemd'"
  notify: Restart uWSGI
