- name: Install uWSGI
  ansible.builtin.apt:
    name: uwsgi
    state: present

- name: Install uWSGI plugin Python3
  ansible.builtin.apt:
    name: uwsgi-plugin-python3
    state: present

- name: Copy the uWSGI configuration for AGAMA application
  ansible.builtin.template:
    src: agama.ini
    dest: /etc/uwsgi/apps-enabled/agama.ini
  notify: Restart uWSGI

- name: Start uWSGI
  ansible.builtin.service:
    name: uwsgi
    state: started
    enabled: yes
