apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    # proxy or direct (Server or Browser in the UI)
    access: proxy
    isDefault: true
    uid: "prometheusUID"
    url: http://VladyslavaSh-2:9090/prometheus

  - name: InfluxDB:latency
    type: influxdb
    access: proxy
    url: http://VladyslavaSh-1:8086
    database: latency
