- name: Create directory for app installation
  ansible.builtin.file:
    path: /opt/agama
    owner: agama
    state: directory
    mode: 0755

- name: Download file agama.py
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/agama.py
    dest: /opt/agama
    mode: 0755

- name: Install packages
  ansible.builtin.apt:
    name:
      - python3-flask-sqlalchemy
      - python3-pymysql
