- name: Create a backup user
  ansible.builtin.user:
    name: backup
#    password: "{{ mysql_backup_password }}"
    home: /home/backup
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: /home/backup/.ssh/id_rsa.pub

- name: Move file with a key
  ansible.builtin.template:
    src: known_hosts
    dest: /home/backup/.ssh/known_hosts
    owner: backup
    group: backup


- name: Create mysql directory
  ansible.builtin.file:
    path: /home/backup/mysql
    state: directory
    owner: backup
    group: backup
    mode: '0744'

- name: Create influxdb directory
  ansible.builtin.file:
    path: /home/backup/influxdb
    state: directory
    owner: backup
    group: backup
    mode: '0744'

- name: Create restore directory
  ansible.builtin.file:
    path: /home/backup/restore
    state: directory
    owner: backup
    group: backup
    mode: '0744'

- name: Install duplicity
  ansible.builtin.apt:
    name: duplicity
