- name: Copy .my.cnf template to conf path
  ansible.builtin.template:
    src: .my.cnf.j2
    dest: /var/lib/prometheus/.my.cnf
  notify:
      - Daemon reload
      - Restart prometheus-mysqld-exporter


- name: Install MySQL Exporter
  ansible.builtin.apt:
    name: prometheus-mysqld-exporter
    state: present


- name: Create MySQL Exporter user
  community.mysql.mysql_user:
     name: "{{ mysql_user }}"
     password: "{{ mysql_exporter_password }}"
     host: "%"
     login_unix_socket: /var/run/mysqld/mysqld.sock
     priv: '*.*:PROCESS,REPLICATION CLIENT,SELECT'


- name: Start MySQL exporter
  ansible.builtin.service:
    enabled: yes
    name: prometheus-mysqld-exporter
    state: started
