- name: Restart keepalived
  ansible.builtin.service:
    name: keepalived
    state: restarted
    enabled: yes

- name: Restart keepalived exporter
  ansible.builtin.service:
    name: prometheus-keepalived-exporter
    state: restarted
    enabled: yes

- name: Daemon reload
  ansible.builtin.systemd:
    daemon_reload: yes
