- name: Install mysql
  ansible.builtin.apt:
    name: mysql-server
    state: present

- name: Restart mysql when changes are applied
  ansible.builtin.copy:
     src: override.cnf
     dest: /etc/mysql/mysql.conf.d/override.cnf
  notify: Restart mysql

- name: MySQL database
  community.mysql.mysql_db:
     name: "{{ mysql_database }}"
     login_unix_socket: /var/run/mysqld/mysqld.sock

- name: MySQL user
  community.mysql.mysql_user:
     name: "{{ mysql_user }}"
     password: "{{ mysql_password }}"
     host: "%"
     login_unix_socket: /var/run/mysqld/mysqld.sock
     priv: "{{ mysql_database }}.*:ALL"
     #priv: '*.*:PROCESS,REPLICATION CLIENT,SELECT'
