- name: Install MySQL
  ansible.builtin.apt:
    name: mysql-server
    state: present

- name: Install PyMysql
  ansible.builtin.apt:
    name: python3-pymysql
    state: present

- name: Copy override.cnf file
  ansible.builtin.copy:
     src: override.cnf
     dest: /etc/mysql/mysql.conf.d/override.cnf
  notify: Restart mysql

- name: MySQL database
  community.mysql.mysql_db:
     name: "{{ mysql_database }}"
     login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create MySQL user
  community.mysql.mysql_user:
     name: "{{ mysql_user }}"
     password: "{{ mysql_password }}"
     host: "%"
     login_unix_socket: /var/run/mysqld/mysqld.sock
     priv: "{{ mysql_database }}.*:ALL"

- name: Start MySQL
  ansible.builtin.service:
     name: mysql
     state: started
     enabled: yes
