- name: Daemon reload
  ansible.builtin.systemd:
    daemon_reload: yes


- name: Restart mysql_exporter
  ansible.builtin.service:
    name: prometheus-mysqld-exporter
    state: restarted
    enabled: yes
