- name: Install Prometheus Node Exporters
  ansible.builtin.unarchive:
    src: "https://github.com/prometheus/node_exporter/releases/download/v1.4.0/node_exporter-1.4.0.linux-amd64.tar.gz"
    dest: /node_exporter/
    remote_src: yes
    validate_certs: no

- name: Restart node_exporter when changes are applied
  ansible.builtin.copy:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
  notify: Restart node_exporter
