#- name: Create a directory
#  ansible.builtin.file:
#    path: /etc/node_exporter
#    state: directory

#- name: Install Prometheus Node Exporters
#  ansible.builtin.unarchive:
#    src: "https://github.com/prometheus/node_exporter/releases/download/v1.4.0/node_exporter-1.4.0.linux-amd64.tar.gz"
#    dest: /etc/node_exporter/
#    remote_src: yes
#    validate_certs: no

- name: Install Node exporter
  ansible.builtin.apt:
     name: prometheus-node-exporter
     state: present


- name: Configure Node exporter
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
  notify:
      - Daemon reload
      - Restart prometheus-node-exporter

- name: Start Node exporter
  ansible.builtin.service:
    name: prometheus-node-exporter
    state: started
    enabled: yes
