- name: Install Bind Exporter
  ansible.builtin.apt:
    name: prometheus-bind-exporter
    state: present

#- name: Add configuration file
#  ansible.builtin.template:
#     dest: /etc/default/prometheus-bind-exporter
#     src: prometheus-bind-exporter
#  notify: Restart bind_exporter
