- name: Restart influxdb
  ansible.builtin.service:
    name: influxdb
    state: restarted
    enabled: yes

- name: Restart telegraf
  ansible.builtin.service:
    name: telegraf
    state: restarted
    enabled: yes
