- name: Install prometheus
  ansible.builtin.apt:
    name: prometheus
    state: present

#- name: Create user prometheus
#  ansible.builtin.user:
#    name: prometheus

- name: prometheus configuration file
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
  notify: Restart prometheus

- name: Add configuration file to /etc/default/prometheus
  ansible.builtin.template:
    src: prometheus.j2
    dest: /etc/default/prometheus
  notify: Restart prometheus

- name: Start prometheus
  ansible.builtin.service:
    name: prometheus
    state: started
    enabled: yes
