- name: Install Nginx exporter
  ansible.builtin.apt:
    name: prometheus-nginx-exporter

- name: Add nginx exporter service
  ansible.builtin.template:
     src: prometheus-nginx-exporter.service.j2
     dest: /etc/systemd/system/prometheus-nginx-exporter.service
  notify: Restart prometheus-nginx-exporter

- name: Start Nginx exporter
  ansible.builtin.service:
    name: prometheus-nginx-exporter
    state: started
    enabled: yes
