- name: Install nginx-prometheus-exporter
  ansible.builtin.apt:
    name: prometheus-nginx-exporter

#- name: Restart exporter when changes are applied
#  ansible.builtin.copy:
#     src: 
#     dest: 
#  notify: Restart nginx-prometheus-exporter
