- name: Restart grafana
  ansible.builtin.service:
    name: grafana
    state: restarted
    enabled: yes

- name: Start grafana
  ansible.builtin.service:
    name: grafana
    state: started
    enabled: yes
