- name: Install docker package
  ansible.builtin.apt:
    name:
      - docker.io
      - python3-docker

- name: Start docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes
